server:
  port: ${SERVER_PORT:8080}
  host: ${SERVER_HOST:localhost}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act3_grades  # Cambia "tu_base_de_datos" por el nombre de tu base de datos
    username: root  # Cambia "tu_usuario" por el nombre de usuario de tu base de datos
    password:   # Cambia "tu_contraseña" por la contraseña de tu base de datos
    driver-class-name: com.mysql.cj.jdbc.Driver  # Controlador de MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true